---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        # trail whitespace
      - id: check-added-large-files
        # prevents giant files from being committed.
      - id: check-case-conflict
        # checks for files that would conflict in case-insensitive filesystems.
      - id: check-merge-conflict
        # checks for files that contain merge conflict strings.
      - id: check-yaml
        # checks yaml files for parseable syntax.
      - id: detect-private-key
        # detects the presence of private keys.
      - id: end-of-file-fixer
        # ensures that a file is either empty, or ends with one newline.
      - id: fix-byte-order-marker
        # removes utf-8 byte order marker.
      - id: mixed-line-ending
        # replaces or checks mixed line ending.
        verbose: true
        types: [text]

  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.33.0
  #   hooks:
  #     - id: markdownlint

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: forbid-tabs

  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.30.0
  #   hooks:
  #     - id: yamllint

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: shellcheck

  - repo: https://github.com/gherynos/pre-commit-java
    rev: v0.2.5  # Use the ref you want to point at
    hooks:
      - id: pmd
        args: ["-R", "pmd_ruleset.xml"]
      - id: cpd
        args: ["--minimum-tokens", "50"]
      - id: checkstyle
        args: ["-c", "checkstyle.xml"]
